import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "900", "300", "700"],
  variable: "--font-roboto",
})

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html>
      <body className={`${roboto.variable} ${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
